# Generated by Django 3.2.13 on 2023-03-18 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='项目名称', max_length=20, verbose_name='项目名')),
                ('leader', models.CharField(help_text='负责人名称', max_length=20, verbose_name='负责人')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '项目表',
                'verbose_name_plural': '项目表',
                'db_table': 'tb_project',
            },
        ),
        migrations.CreateModel(
            name='TestEnv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='测试环境名称', max_length=20, verbose_name='环境名称')),
                ('global_variable', models.JSONField(blank=True, default=dict, null=True, verbose_name='全局变量')),
                ('debug_global_variable', models.JSONField(blank=True, default=dict, null=True, verbose_name='debug模式全局变量')),
                ('host', models.CharField(blank=True, max_length=100, null=True, verbose_name='base_url地址')),
                ('db', models.JSONField(blank=True, default=list, null=True, verbose_name='数据库配置')),
                ('headers', models.JSONField(blank=True, default=dict, null=True, verbose_name='全局请求头')),
                ('global_func', models.TextField(blank=True, default='"""\n自定义全局工具函数\n============================\n"""\nfrom apitestengine.core.tools import *', null=True, verbose_name='全局函数')),
                ('project', models.ForeignKey(help_text='项目id', on_delete=django.db.models.deletion.CASCADE, related_name='test_envs', to='projects.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '测试环境表',
                'verbose_name_plural': '测试环境表',
                'db_table': 'tb_test_env',
            },
        ),
        migrations.CreateModel(
            name='Interface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='接口名称')),
                ('url', models.CharField(help_text='接口地址，url', max_length=200, verbose_name='接口地址')),
                ('method', models.CharField(help_text='http请求方法', max_length=20, verbose_name='请求方法')),
                ('type', models.SmallIntegerField(choices=[(1, '项目接口'), (2, '三方接口')], default=1, max_length=20, verbose_name='接口类型')),
                ('project', models.ForeignKey(help_text='项目id', on_delete=django.db.models.deletion.CASCADE, related_name='interfaces', to='projects.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '接口表',
                'verbose_name_plural': '接口表',
                'db_table': 'tb_interface',
            },
        ),
    ]
