# Generated by Django 3.2.13 on 2023-03-18 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interface',
            name='type',
            field=models.SmallIntegerField(choices=[(1, '项目接口'), (2, '三方接口')], default=1, verbose_name='接口类型'),
        ),
    ]
