# Generated by Django 3.2.13 on 2023-03-23 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_interface_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interface',
            name='type',
            field=models.CharField(choices=[('1', '项目接口'), ('2', '三方接口')], default='1', max_length=10, verbose_name='接口类型'),
        ),
    ]
