# Generated by Django 3.2.13 on 2023-03-18 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_alter_interface_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SceneData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort', models.IntegerField(blank=True, default=0, verbose_name='执行顺序')),
            ],
            options={
                'verbose_name': '场景步骤',
                'verbose_name_plural': '场景步骤',
                'db_table': 'tb_scene_data',
            },
        ),
        migrations.CreateModel(
            name='TestStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='用例名称')),
                ('request', models.JSONField(blank=True, default=dict, verbose_name='请求参数')),
                ('headers', models.JSONField(blank=True, default=dict, verbose_name='请求头')),
                ('file', models.JSONField(blank=True, default=list, verbose_name='上传文件参数')),
                ('setup_script', models.TextField(blank=True, default='# 前置脚本(python):\n# global_tools:全局工具函数\n# data:用例数据 \n# env: 局部环境\n# ENV: 全局环境\n# db: 数据库操作对象\n', verbose_name='前置脚本')),
                ('teardown_script', models.TextField(blank=True, default='# 后置脚本(python):\n# global_tools:全局工具函数\n# data:用例数据 \n# response:响应对象response \n# env: 局部环境\n# ENV: 全局环境\n# db: 数据库操作对象\n', verbose_name='后置脚本')),
                ('interface', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.interface', verbose_name='所属接口')),
            ],
            options={
                'verbose_name': '测试步骤表',
                'verbose_name_plural': '测试步骤表',
                'db_table': 'tb_test_step',
            },
        ),
        migrations.CreateModel(
            name='TestScene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='测试场景名')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='test_scenes', to='projects.project', verbose_name='所属项目')),
                ('steps', models.ManyToManyField(help_text='包含的测试步骤', through='testplans.SceneData', to='testplans.TestStep', verbose_name='步骤')),
            ],
            options={
                'verbose_name': '测试场景',
                'verbose_name_plural': '测试场景',
                'db_table': 'tb_test_scene',
            },
        ),
        migrations.CreateModel(
            name='TestPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='计划名称')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='test_plans', to='projects.project', verbose_name='所属项目')),
                ('scenes', models.ManyToManyField(help_text='包含的测试场景', to='testplans.TestScene', verbose_name='测试场景')),
            ],
            options={
                'verbose_name': '测试计划',
                'verbose_name_plural': '测试计划',
                'db_table': 'tb_test_plan',
            },
        ),
        migrations.AddField(
            model_name='scenedata',
            name='scene',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='testplans.testscene', verbose_name='场景'),
        ),
        migrations.AddField(
            model_name='scenedata',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='testplans.teststep', verbose_name='步骤'),
        ),
    ]
