# Generated by Django 3.2.13 on 2023-04-08 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_interface_type'),
        ('testplans', '0003_alter_testplan_scenes'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrontabTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='任务名称')),
                ('rule', models.CharField(default='* * * * *', max_length=80, verbose_name='定时规则')),
                ('tester', models.CharField(blank=True, max_length=20, null=True, verbose_name='测试员')),
                ('status', models.BooleanField(default=False, verbose_name='是否开启')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('env', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.testenv', verbose_name='测试环境')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='testplans.testplan', verbose_name='执行计划')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crontab_tasks', to='projects.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '定时任务',
                'verbose_name_plural': '定时任务',
                'db_table': 'tb_crontab_task',
            },
        ),
    ]
