# Generated by Django 3.2.13 on 2023-04-08 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testplans', '0004_crontabtask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testplan',
            name='scenes',
            field=models.ManyToManyField(blank=True, help_text='包含的测试场景', to='testplans.TestScene', verbose_name='测试场景'),
        ),
    ]
